language: node_js
node_js: 14
cache: yarn
jobs:
  include:
    - stage: release
      node_js: 14
      deploy:
        skip_cleanup: true
        provider: script
        script: npx semantic-release
