name: Test and Release

env:
  MAIN_REF: refs/heads/master

on:
  push:
    branches: ["**"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

# Publish to npm with OIDC
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        # See https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          version: 2026.8.14

      # for npx publish
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build

      - name: Test packages
        run: bun run test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost

      - name: Capture new release versions
        if: ${{ github.ref == env.MAIN_REF }}
        run: |
          if npx @changesets/cli status --output=release.json; then
            echo "CHANGED_PACKAGES=$(jq -r '.releases | map(.name + "@" + .newVersion) | join(", ")' release.json)" >> "$GITHUB_ENV"
            rm release.json
          fi

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == env.MAIN_REF }}
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
          title: "Release ${{env.CHANGED_PACKAGES}}"
          commit: "Release ${{env.CHANGED_PACKAGES}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
